### ISSUE TITLE
Class which contains static methods only is considered as an interface

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/FSharpLint#100]
![image](https://cloud.githubusercontent.com/assets/873919/8511358/57fa872a-231a-11e5-9e2b-b98f0df7eb75.png)

https://github.com/fsharp/FSharp.Data/blob/7caa9ed507dc0c69abc39ed438acb5af81080abd/src/Csv/CsvExtensions.fs#L14

**Comment by duckmatt** [comment]
Thanks for reporting this, it should be fixed in [`0.0.3`](https://www.nuget.org/packages/FSharpLint.Core/)

**Comment by vasily-kirichenko** [comment]
It's not fixed in 0.0.3

**Comment by vasily-kirichenko** [comment]
Fixed in 0.0.5
