### ISSUE TITLE
"Useless binding" rule triggers in wrong context

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/FSharpLint#101]
![image](https://cloud.githubusercontent.com/assets/873919/8511372/d3b6dbde-231a-11e5-9f67-65c776261544.png)

https://github.com/fsharp/FSharp.Data/blob/7caa9ed507dc0c69abc39ed438acb5af81080abd/src/Xml/XmlRuntime.fs#L96

**Comment by duckmatt** [comment]
Thanks for reporting this, it should be fixed in [`0.0.3`](https://www.nuget.org/packages/FSharpLint.Core/)

**Comment by vasily-kirichenko** [comment]
It's not fixed in 0.0.3.

**Comment by vasily-kirichenko** [comment]
Fixed in 0.0.5
