### ISSUE TITLE
(Almost) duplicated lint warnings on mutually recursive values

### ISSUE THREAD

**Issue by dungpa** [fsprojects/FSharpLint#102]
![image](https://cloud.githubusercontent.com/assets/941060/8511499/19f347e6-231a-11e5-9f47-bc2c3099b567.png)

From the warnings, it's difficult to know which warning is for which function.

Moreover, "Lambda Functions" should be written as "Lambda functions" for consistency with other rules.

Source: https://github.com/fsprojects/VisualFSharpPowerTools/blob/ec6c574281f4103819d421f7e3734f00f1b1c142/src/FSharpVSPowerTools.Core/Utils.fs#L424-L441

**Comment by duckmatt** [comment]
Would it help to have an option that stops a warning from being within the range of another warning of the same type?

I've updated the grammar, I think a lot of the warning messages could do with re-wording at some point

**Comment by dungpa** [comment]
Yes, it would.

I think names of bindings should be used in warning messages whenever possible.

**Comment by vasily-kirichenko** [comment]
I confirm it's fixed in 0.0.3.
