### ISSUE TITLE
False positives inside pattern matching

### ISSUE THREAD

**Issue by dungpa** [fsprojects/FSharpLint#103]
![image](https://cloud.githubusercontent.com/assets/941060/8511532/27c669d2-231c-11e5-81af-18dab90e13dd.png)

Underscore identifiers are perfectly valid inside pattern matching. 

Source: https://github.com/fsprojects/VisualFSharpPowerTools/blob/ec6c574281f4103819d421f7e3734f00f1b1c142/src/FSharpVSPowerTools.Core/LanguageService.fs#L58-L61

**Comment by duckmatt** [comment]
Is this used to make a wildcard more readable? If not why is a wildcard not used as in `GetFormatSpecifierLocations` above? If so it might make sense for underscore rule to only be applied to module level bindings

**Comment by dungpa** [comment]
Yes, they have been used as mnemonic wildcards. I think it makes sense to relax the rules in the context of pattern matching.

**Comment by dungpa** [comment]
Fixed in 0.0.4.
