### ISSUE TITLE
FSharpLint.Core package should depend on external NuGet packages

### ISSUE THREAD

**Issue by dungpa** [fsprojects/FSharpLint#104]
Normally a library should not swallow dependencies. It should give API consumers a chance to resolve dependencies. We get these warnings in VFPT when using FSharpLint.Core:

> Warning	8	No way to resolve conflict between "FSharp.Compiler.Service, Version=0.0.90.0, Culture=neutral, PublicKeyToken=null" and "FSharp.Compiler.Service, Version=0.0.89.0, Culture=neutral, PublicKeyToken=null". Choosing "FSharp.Compiler.Service, Version=0.0.90.0, Culture=neutral, PublicKeyToken=null" arbitrarily.	C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets	1635	5	FSharpVSPowerTools.Logic

It's much better if `FSharpLint.Core` depends on FCS, FParsec i.e. any package it uses.

**Comment by duckmatt** [comment]
Thanks for reporting this, that's true, I'll get that sorted for when the latest version of the package is uploaded

**Comment by duckmatt** [comment]
Is it possible to handle binding redirects in a visual studio extension? FParsec package on NuGet references 4.0.0.0 and needs a binding redirect to 4.3.0.0, I've built the assemblies targeting 4.3.0.0 and included them in the `lib` directory because binding redirects couldn't be added to the MSBuild task

**Comment by dungpa** [comment]
VS extensions don't support binding redirects yet. For now, a self-built version of FParsec is OK for us since we haven't had dependencies on FParsec.

**Comment by duckmatt** [comment]
Okay great, the latest version of the package [`0.0.3`](https://www.nuget.org/packages/FSharpLint.Core/) now has `FSharp.Compiler.Services` as a nuget dependency
