### ISSUE TITLE
API to write configuration to file

### ISSUE THREAD

**Issue by duckmatt** [fsprojects/FSharpLint#106]
For tools to be able to provide an update-able interface to the configuration they'll need a way to write configuration changes to a file.

Configuration settings will need a reference to what config file they came from in memory (so we only write the necessary overridden settings to the file).

**Comment by dungpa** [comment]
What's status of this issue? It's an important building block to complete FSharpLint integration to VFPT.

**Comment by duckmatt** [comment]
I'm hoping to have the FSharpLint API side of things done this afternoon

**Comment by duckmatt** [comment]
There's a branch that now has writing configs in memory back to xml implemented, I'm working on a configuration management class that will allow for easily finding the config files for a project, keeping them individually in memory, and updating them on the file system - this will be the backend to any UI used for setting the configuration. Hopefully that should be done this week, and I'll try to do the UI for the configuration of the linter in VFPT alongside this

**Comment by dungpa** [comment]
Cool. Thanks for the update.

There is no need to rush. At least we're making progress :-).

/cc @vasily-kirichenko
