### ISSUE TITLE
Wrong warning in object initializer

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/FSharpLint#108]
![image](https://cloud.githubusercontent.com/assets/873919/8748077/aa3a6aa2-2ca0-11e5-8982-df1f95481e2d.png)

**Comment by duckmatt** [comment]
Thanks, seems to occur when there are type arguments

**Comment by duckmatt** [comment]
This should be fixed in [`0.0.5`](https://www.nuget.org/packages/FSharpLint.Core/0.0.5)

**Comment by vasily-kirichenko** [comment]
I confirm it's fixed.
