### ISSUE TITLE
Wrong warning "fun _ -> () can be refactored into ignore" 

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/FSharpLint#109]
![image](https://cloud.githubusercontent.com/assets/873919/8763126/d6b793fa-2d97-11e5-8c44-35d83adac9c5.png)
![image](https://cloud.githubusercontent.com/assets/873919/8763132/f88ec534-2d97-11e5-8568-05df3b93fcbe.png)

**Comment by duckmatt** [comment]
Thanks, I think this might be something that only type checker is going to be able to handle (it currently doesn't so that needs to be fixed). I might get it so that the non type checked lint will fallback to not giving lambda hints when a parameter in a method
