### ISSUE TITLE
Add more rules to XmlDocumentation analyser

### ISSUE THREAD

**Issue by duckmatt** [fsprojects/FSharpLint#11]
https://github.com/duckmatt/FSharpLint/blob/master/src/FSharpLint.Rules/XmlDocumentation.fs

Rules off the top of my head to be added:

Module comment
Function (not inside of a binding expression) comment
Member comment
Type comment
Enum case comment
Union case comment
Record field comment

**Comment by jhamm** [comment]
I will work on this one. jhamm/FSharpLint 

* [ ] Module comment
* [ ] Function (not inside of a binding expression) comment
* [ ] Member comment
* [x] Type comment
* [ ] Enum case comment
* [ ] Union case comment
* [ ] Record field comment

**Comment by duckmatt** [comment]
That would be great. 

When I've been writing new rules the easiest way I've found to do it is to add a test you'd expect to generate a lint warning, and another test with the same code fixed to not generate a lint warning. Then you can put a breakpoint on the visitor and run the test under debug to compare the difference in the ASTs to see what needs to be matched against.

Let me know if you have any problems/questions

**Comment by jhamm** [comment]
Thanks! That's good advice.

**Comment by duckmatt** [comment]
Thanks @jhamm
