### ISSUE TITLE
Publish new FSharpLint.Core version compatible with F# 4.0

### ISSUE THREAD

**Issue by dungpa** [fsprojects/FSharpLint#110]
F# 4.0 comes out tomorrow with VS 2015 RTM (July 20, 2015).

We're in process of moving VFPT to F# 4.0. In order to use FSharpLint.Core, we need a new NuGet package that depends on this FCS version https://www.nuget.org/packages/FSharp.Compiler.Service/1.4.0-beta.

The main reason is that there are a few breaking changes on untyped ASTs.

**Comment by duckmatt** [comment]
Thanks for letting me know, I've added [`0.0.6-beta`](https://www.nuget.org/packages/FSharpLint.Core/0.0.6-beta) which has a dependency on FCS `1.4.0-beta`

**Comment by dungpa** [comment]
Thanks. That was quick. It seems there is no API breakage as I worried.

**Comment by dungpa** [comment]
@duckmatt FYI: FCS 1.4.0.1 has been released https://www.nuget.org/packages/FSharp.Compiler.Service/1.4.0.1. From the next version, we can remove `beta` tag from `FSharpLint.Core` NuGet package.

**Comment by duckmatt** [comment]
Thanks, I'll try to get a new version up this weekend
