### ISSUE TITLE
Suggest to use `use` instead of `let` for local IDisposable values

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/FSharpLint#111]
http://vfpt.uservoice.com/forums/247560-general/suggestions/6785027-suggest-to-use-use-instead-of-let-for-local-id

**Comment by duckmatt** [comment]
Thanks for the suggestion, this would be good to have. I think there are a few edge cases it would need to handle (e.g. `IDisposable` value in `let` binding in a function that returns a object expression which closes over the let binding and disposes of it in its `Dispose` method)

Might also be good for this to warn if `new` is used in a `let` binding so no type checking will need to be done, if it's fixed according to that they'll get a message from the compiler

**Comment by vasily-kirichenko** [comment]
Warning on redundant `new` would be cool (I mean if a type does not implement `IDisposable`).

**Comment by stanuku** [comment]
Hello - I would like to work on this issue. Just wanted to take this as an opportunity to give back to the F# community. I'm an experienced C# developer and started to learn (and love) F#. 

Any suggestions on pre-requisite reading/reference material about the specific concepts required for this library that I should refer to, that will aid me?

Thanks

**Comment by duckmatt** [comment]
Hi @stanuku, that's great to hear :) 

The major dependency that'll be worth having a read about is [FSharp.Compiler.Services](https://fsharp.github.io/FSharp.Compiler.Service/), this is what the linter is using to go from source code to AST. Currently we're using the untyped tree, to get the type information [we're using the symbol resolver](https://github.com/fsprojects/FSharpLint/blob/master/src/FSharpLint.Core/Rules/NameConventions.fs#L232). After having a read of that a good way to get stuck into it is to add a couple of [tests](https://github.com/fsprojects/FSharpLint/blob/master/tests/FSharpLint.Core.Tests/Rules/TestBindingRules.fs) and run the test in debug to step through the [source](https://github.com/fsprojects/FSharpLint/blob/master/src/FSharpLint.Core/Rules/Binding.fs) to inspect the AST that has been generated from the source.

The feature has been discussed as being implemented as a compiler warning - related threads: [Github](https://github.com/Microsoft/visualfsharp/issues/1346) and [User Voice](https://fslang.uservoice.com/forums/245727-f-language/suggestions/15448122-add-a-warning-for-new-keyword-used-on-types-which). It'd be a great addition to the linter! The user voice is a good spec of what we'd probably want to be doing here

Hope this helps, if you run into any problems/have any questions let me know

**Comment by stanuku** [comment]
Thank you Matt, I'll be on it.

**Comment by stanuku** [comment]
@duckmatt: After cloning the fork locally, I'm just having to go through so many hoops get build.fsx run without failure. It seems to me that a lot of it has to do with the missing 'tools' folder inside packages.build.fsx referes to FAKE, nunit3-console.exe etc also this https://github.com/fsharp/FAKE/issues/926. 

Just wondering if there is a 'steps for developers' to get setup locally?. - Thanks!

**Comment by duckmatt** [comment]
Sorry to hear you're having problems getting it running. If you run `build.cmd` it should pull down all the tooling dependencies (and build the solution)

**Comment by stanuku** [comment]
@duckmatt: That worked great!. Sorry, I didn't understand the paket's features well enough to realize that the dependencies file is creating the Tools group inside the packages folder. Thanks for your help. I've started reviewing the compiler services.

**Comment by duckmatt** [comment]
No problem, it's not very clear how to build, I'll try to get some build instructions added to the readme. glad to hear it's running :)
