### ISSUE TITLE
Wrong suggestion to replace lambda to pointfree constructor application

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/FSharpLint#113]
![image](https://cloud.githubusercontent.com/assets/873919/8871212/4994c402-31fc-11e5-9752-0b14f2a65081.png)
![image](https://cloud.githubusercontent.com/assets/873919/8871225/66fa3446-31fc-11e5-866b-beefba910fc1.png)

**Comment by vasily-kirichenko** [comment]
Where `Sha1` is a type.

**Comment by duckmatt** [comment]
Thanks, I believe this should be possible in F# 4 so the fix will need to check if it's an earlier version (and unfortunately looks like it fix will only be for when type checking is enabled)
