### ISSUE TITLE
Local variables may contain underscores

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/FSharpLint#119]
![image](https://cloud.githubusercontent.com/assets/873919/9305576/15630218-44fb-11e5-8e53-96604f58a883.png)

**Comment by curtnichols** [comment]
It's not just local variables, it's also function arguments. Perhaps more.

**Comment by duckmatt** [comment]
This has been fixed in [0.0.13](https://www.nuget.org/packages/FSharpLint.Core/) of the API
