### ISSUE TITLE
Property lookup vs. pointless function

### ISSUE THREAD

**Issue by forki** [fsprojects/FSharpLint#130]
![image](https://cloud.githubusercontent.com/assets/57396/10242937/efe334d6-68f4-11e5-9da6-79a373ebe514.png)

how?

**Comment by duckmatt** [comment]
Thanks, this is a bug

**Comment by duckmatt** [comment]
This has been fixed in [0.0.13](https://www.nuget.org/packages/FSharpLint.Core/) of the API
