### ISSUE TITLE
Enhance error message

### ISSUE THREAD

**Issue by OkayX6** [fsprojects/FSharpLint#132]
Hey,

I was looking at this bug https://github.com/fsprojects/VisualFSharpPowerTools/issues/697, and was surprised to see this warning message appear. I think it comes from Lint.
I think it should be a little bit modified: it is perfectly fine to use Uppercase when they're supposed to match a DU case, a literal constant or an active pattern.

![image](https://cloud.githubusercontent.com/assets/1169339/10352492/a4a3fc26-6d4f-11e5-984a-7f98bffdd61a.png)

Thanks :)
Denis

**Comment by duckmatt** [comment]
Hi, this is a compiler warning (looks like `Pattern1` active pattern is out of scope), in VFPT the lint suggestions would be preceded by `Lint:` e.g.

![](https://cloud.githubusercontent.com/assets/873919/10359832/d5b40784-6da4-11e5-810e-e39a6d27518a.png)

**Comment by OkayX6** [comment]
Aaaah ahah sorry to have bothered you then.

**Comment by OkayX6** [comment]
I could suggest it to Visual F#.

**Comment by duckmatt** [comment]
No worries :)
