### ISSUE TITLE
Try using ILmerge for the task dlls

### ISSUE THREAD

**Issue by duckmatt** [fsprojects/FSharpLint#134]
For the FAKE task and MSBuild task all the lint assemblies are loaded into new separate app domains so they don't re-use any existing assemblies in the host process (MSBuild task picks up assemblies from F# Power Tools), unfortunately it often seems to cause problems, see: https://github.com/fsprojects/FSharpLint/issues/131 and https://github.com/fsprojects/FSharpLint/issues/121 for outstanding current related issues. Using ILMerge to merge the assemblies into a single assembly should solve these problems once and for all

This should simplify the code a bit, and also remove the remaining C#!

**Comment by duckmatt** [comment]
This is going to need a new approach, combining the third party assemblies with ILMerge is going to cause a conflict of types etc

**Comment by et1975** [comment]
Beaware, ILMerged assemblies don't work so well on mono..
