### ISSUE TITLE
Object expressions is mistaken for tuple

### ISSUE THREAD

**Issue by zbilbo** [fsprojects/FSharpLint#141]
code like 

let createMyObject a b c d e f =
 MyObject
 (
   Prop1 = a
   Prop2 = b
   Prop3 = c
   Prop4 = d
   Prop5 = e
   Prop6 = f
  )

will then flag "Tuples expected to have maximum X items"...

**Comment by duckmatt** [comment]
Thanks for the report

**Comment by bleis-tift** [comment]
Is this the same problem?

![image](https://cloud.githubusercontent.com/assets/169348/11026275/78f8f41e-86ea-11e5-8007-b7175ece8a79.png)

**Comment by zbilbo** [comment]
Im not sure if the "is this the same problem"-question is for me or @duckmatt, but if it is for me I would say: absolutely no.

The above is related to tuples and as such it is in fact entirely correct according to the definition of this lint-rule to give the shown warning.

Object expressions and tuples are syntactically equal (kind of), but are different.

And of course it might be argued that I should not write code as the above and go for something like:
let createMyObject a b c d e f =
 let o = MyObject()
 o.Prop1 <- a
 o.Prop2 <- b
 o.Prop3 <- c
 o.Prop4 <- d
 o.Prop5 <- e
 o.Prop6 <- f
 o

And possibly even throw in a new ahead of MyObject(): let o = new MyObject()

The point being is that my code is not a tuple and unless there exists some rule for not using objects like in my code it should  (if possible) not warn either.

So it might end up with the bug being that it says "Tuple" instead of "Object expression" ;-)

**Comment by duckmatt** [comment]
The problem behind these issues is that the type checker is not being used for performance reasons and as such at this point can't tell whether `MyObject` is a function or a type.

There was a slight attempt to mitigate this by using the `isAtomic` flag on the function application to try and attempt to tell whether the tuple is for a function or a method/constructor, but that's no guarantee (as you can see above: the first `A` constructor has no warning but the second does).

This rule will have to not warn for tuples within function applications in the AST when not using type checking

**Comment by zbilbo** [comment]
@duckmatt guessed as much (that it would be pretty hard to dichotomize between objects vs tuples vs otherstuff)...

and its no biggie at all. so a "wont fix" on this issue is more than fine with me...

its not like i will uninstall this fslint & powertools due to this issue not being fixed ;-)

**Comment by duckmatt** [comment]
This has been fixed in [0.0.13](https://www.nuget.org/packages/FSharpLint.Core/) of the API
