### ISSUE TITLE
Merge configs

### ISSUE THREAD

**Issue by TWith2Sugars** [fsprojects/FSharpLint#142]
I like that I can specify hints etc in a Settings.FSharpLint, however I'd prefer to add to the default rather than carry around the whole hints file.

**Comment by duckmatt** [comment]
That's a good idea especially as the ignore files section which is structured in the config very similarly already has a add/overwrite option

**Comment by duckmatt** [comment]
This has been implemented and will be included in the next release https://github.com/fsprojects/FSharpLint/issues/229
