### ISSUE TITLE
Single trailing whitespace is not detected

### ISSUE THREAD

**Issue by TeaDrivenDev** [fsprojects/FSharpLint#147]
It takes at least two trailing whitespace characters to trigger the rule; shouldn't one be enough?

![screenshot - 29 12 2015 15_18_47](https://cloud.githubusercontent.com/assets/2247219/12035741/a5e19f04-ae3f-11e5-9ddc-75b4226f3325.png)

(This is FSharpLint in Visual F# Power Tools in Visual Studio 2015.)

**Comment by duckmatt** [comment]
The number of whitespace characters allowed at the end of the line can be configured here:

![image](https://cloud.githubusercontent.com/assets/3247369/12037327/de4026e4-ae45-11e5-909b-a4e1db82500f.png)

The [default is `1`](https://github.com/fsprojects/FSharpLint/blob/master/src/FSharpLint.Framework/DefaultConfiguration.FSharpLint#L268) , with `OneSpaceAllowedAfterOperator` it might make sense to drop the default to `0`

**Comment by TeaDrivenDev** [comment]
Ah, thanks; I didn't even consider the possibility this might be configurable. ;-) Good; that's that. :-)
