### ISSUE TITLE
Question about Paket usage in this project

### ISSUE THREAD

**Issue by baronfel** [fsprojects/FSharpLint#151]
Hi Matt, first off thanks so much for this project!  I was looking through it before you messaged on the Fantomas issue where I've got a PR outstanding, and I noticed that you weren't using any paket.references files in your project to declare the dependencies for those projects, and you were having to manually script out your package builds in the build.fsx as a result.  Would you accept a PR to switch to using paket.references and paket.template files to automate some of this book-keeping and make things a bit more declarative?

**Comment by duckmatt** [comment]
Hi Chester, thanks for pointing this out, I'd definitely accept the PR!

**Comment by baronfel** [comment]
Great!  I'll try to shoot something your way soon so you can evaluate it.

**Comment by duckmatt** [comment]
Thank you for pointing this out, got around to implementing it recently, please let me know if any of it does not look correct

56302f9584d9e2e463376dfa4ef3e1190fa43f87
ff63e63f8e72f29cb5f60c5e2c982a4980a03f21
69abe6228ca0be7c30cb534a47108a21fa9b8283
