### ISSUE TITLE
Why does FSharpLint prefer || over 'or'?

### ISSUE THREAD

**Issue by robertwharvey** [fsprojects/FSharpLint#158]
One of the possible warnings is "In F# code, use 'e1 || e2' instead of 'e1 or e2'".

What is the rationale there?  Wouldn't the 'or' form be more readable?

**Comment by duckmatt** [comment]
This looks like a custom hint that has been added to the config you're using - this rule isn't in the tool by default

**Comment by duckmatt** [comment]
It's a [compiler warning](https://github.com/Microsoft/visualfsharp/blob/1f19d213907d45ca6c5a27aa9cb2910f60b81a9e/src/fsharp/FSharp.Core/prim-types.fsi#L1053)

**Comment by robertwharvey** [comment]
I know what it is.  Why is it there?

**Comment by robertwharvey** [comment]
Thanks.
