### ISSUE TITLE
Provide pre-compile binary.

### ISSUE THREAD

**Issue by lijunle** [fsprojects/FSharpLint#160]
I search for a long time. Where can I download the pre-compile EXE?

I suppose it will be inside NUGET package, but it does not. :disappointed:

**Comment by duckmatt** [comment]
Hi, sorry about that, it's not currently hosted anywhere - we'll include it in all future releases of the nuget package (I'll put it in a zip in the releases section on this github when I get home tonight)

**Comment by lijunle** [comment]
Hey, @duckmatt . Thank you for reply!

I checked the zip in the release page, it is for the source code, any pre-compiled binaries?

**Comment by duckmatt** [comment]
Hi, it can now be [found here](https://ci.appveyor.com/project/duckmatt/fsharplint-231/build/artifacts), the latest version is pretty experimental (on its way towards a version 1 beta) - if you need an earlier version it'll probably need to be built locally 

Thanks for highlighting this, it's good to now have a deploy located somewhere, I'll be looking at cleaning it up a bit as it seems to contain a lot of unnecessary files

**Comment by lijunle** [comment]
@duckmatt Thank you for your great job! 😸
