### ISSUE TITLE
Unable to find the file 'FSharp.Core.dll'

### ISSUE THREAD

**Issue by mbergin** [fsprojects/FSharpLint#171]
### Description

Found a possible bug today that I wanted to try to fix myself. However I couldn't get the project to build:

- Tests aren't able to find FSharp.Core.dll.
- fsharplint.exe can't find Microsoft.Build.Framework, Version=12.0.0.0.

I'm guessing this is some dependency I don't have. Any troubleshooting tips?

Thanks

### Repro steps

```
git clone https://github.com/fsprojects/FSharpLint.git
build
```

> ...
Unable to find version '3.33.0' of package 'FAKE.Lib'.
Unable to find version '0.0.82' of package 'FSharp.Compiler.Service'.
...

```
.nuget\nuget
```

> NuGet Version: 2.8.60318.667
...

```
# Decide nuget is too old
curl -o .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
build
```

> ...
Failed to lint C:\Users\x\Source\Repos\FSharpLint\tests\FSharpLint.FunctionalTest.TestedProject\FSharpLint.FunctionalTest.TestedProject.fsproj. Failed with: Lint failed while analysing C:\Users\x\Source\Repos\FSharpLint\tests\FSharpLint.FunctionalTest.TestedProject\FSharpLint.FunctionalTest.TestedProject.fsproj.
Failed with: failed to parse file startup, message: internal error: BuildFrameworkTcImports: no resolution of 'FSharp.Core.dll', failed to parse file unknown, message: Unable to find the file 'FSharp.Core.dll' in any of
 C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1
 C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Facades
 C:\Users\x\Source\Repos\FSharpLint\tests\FSharpLint.FunctionalTest.TestedProject
 C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\
...

```
# Try running it despite test fail
bin\fsharplint -source "let x=1"
```

> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Framework, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
...

### Related information 

* Visual Studio Community 2015 14.0.25425.01 Update 3
* Windows 10.0.10586
* Branch c124fdf
* .NET Runtime 4.6.01038

**Comment by mbergin** [comment]
Full build output:
[build.txt](https://github.com/fsprojects/FSharpLint/files/401645/build.txt)

**Comment by duckmatt** [comment]
Hi, sorry about this and thanks for the report, looks like an unfortunate series of issues. 

The nuget errors you got look like a network problem or nuget being down - the build servers are pulling the dependencies down

The FSharp.Core issue is definitely a bug (only occurring on some setups - a machine I have access to is also producing the same test errors, it's also windows 10, vs 2015 update 3), I'll try to get this fixed asap

The Build.Framework assembly can be installed via Microsoft Build Tools, although ideally that's not something users of the tool should need to do, would it be possible to get the log of the application trying to load `Microsoft.Build.Framework` on your machine via fusion log?

**Comment by mbergin** [comment]
Hi. Thanks for checking this out. Here's the fuslogvw output

```
*** Assembly Binder Log Entry  (05/08/2016 @ 00:43:17) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Users\matt\Source\Repos\FSharpLint\bin\fsharplint.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.Build.Framework, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Users/matt/Source/Repos/FSharpLint/bin/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = fsharplint.exe
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\matt\Source\Repos\FSharpLint\bin\fsharplint.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/Users/matt/Source/Repos/FSharpLint/bin/Microsoft.Build.Framework.DLL.
LOG: Attempting download of new URL file:///C:/Users/matt/Source/Repos/FSharpLint/bin/Microsoft.Build.Framework/Microsoft.Build.Framework.DLL.
LOG: Attempting download of new URL file:///C:/Users/matt/Source/Repos/FSharpLint/bin/Microsoft.Build.Framework.EXE.
LOG: Attempting download of new URL file:///C:/Users/matt/Source/Repos/FSharpLint/bin/Microsoft.Build.Framework/Microsoft.Build.Framework.EXE.
LOG: All probing URLs attempted and failed.

*** Assembly Binder Log Entry  (05/08/2016 @ 00:43:17) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Users\matt\Source\Repos\FSharpLint\bin\fsharplint.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.Build.Framework, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Users/matt/Source/Repos/FSharpLint/bin/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = fsharplint.exe
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\matt\Source\Repos\FSharpLint\bin\fsharplint.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/Users/matt/Source/Repos/FSharpLint/bin/Microsoft.Build.Framework.DLL.
LOG: Attempting download of new URL file:///C:/Users/matt/Source/Repos/FSharpLint/bin/Microsoft.Build.Framework/Microsoft.Build.Framework.DLL.
LOG: Attempting download of new URL file:///C:/Users/matt/Source/Repos/FSharpLint/bin/Microsoft.Build.Framework.EXE.
LOG: Attempting download of new URL file:///C:/Users/matt/Source/Repos/FSharpLint/bin/Microsoft.Build.Framework/Microsoft.Build.Framework.EXE.
LOG: All probing URLs attempted and failed.

*** Assembly Binder Log Entry  (05/08/2016 @ 00:43:17) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Users\matt\Source\Repos\FSharpLint\bin\fsharplint.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.Build.Framework, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Users/matt/Source/Repos/FSharpLint/bin/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = fsharplint.exe
Calling assembly : FSharp.Compiler.Service, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\matt\Source\Repos\FSharpLint\bin\fsharplint.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: The same bind was seen before, and was failed with hr = 0x80070002.
ERR: Unrecoverable error occurred during pre-download check (hr = 0x80070002).
```

**Comment by mbergin** [comment]
The nuget thing turned out to be my user nuget.config having only the v3 API endpoint. If I change
`<add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />`
to `<add key="nuget.org" value="https://nuget.org/api/v2" protocolVersion="2" />`
then it works fine with the checked in version of nuget.exe. I'd hazard a guess the build server has this line.

**Comment by duckmatt** [comment]
Great, thank you. I've pushed some changes to master so it should now build and have all tests pass on your machine

**Comment by mbergin** [comment]
Perfect. Works for me now, thanks.

**Comment by duckmatt** [comment]
Thanks, let me know if you hit any problems looking for that possible bug

**Comment by mbergin** [comment]
I couldn't reproduce it against master, so I hope it'll disappear from F# Power Tools next time they upgrade FSharpLint.

**Comment by duckmatt** [comment]
Ah yes, I recently [added a regression test for that bug](https://github.com/fsprojects/FSharpLint/commit/c124fdf0be7375bc6f360a114f6f4510cba08c7d) and noticed it had been fixed at some point. When the next version of VFPT is released it'll include many improvements to the linter - much more performant and a more sensible default configuration :)
