### ISSUE TITLE
Configuration Manager not working

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsprojects/FSharpLint#172]
I've tried using [ConfigurationManager](https://github.com/fsprojects/FSharpLint/blob/master/src/FSharpLint.Core/Application/ConfigurationManager.fs) for tracking configurations in FSAC.

Unfortunately `GetConfigurationForProject` always returns default configuration. 

After bit of investigation I've realized that the problem is in internal representation of state, `ConfigurationManager` is using `Dictionary<DirectoryInfo, Configuration>`   

Unfortunately we live in lovely .Net world and DirectoryInfo doesn't override equality and GetHashCode to use structural comparison so:

`(DirectoryInfo @"C:\").GetHashCode () = (DirectoryInfo @"C:\").GetHashCode ()`
gives  `false` 

I guess just full directory path should be used as a key, will do PR changing it tomorrow.

**Comment by duckmatt** [comment]
Sorry about that. Thank you for the PR, I'll get a new package up. I'll look at cleaning up the configuration api (it seems to be spread/duplicated across multiple files: ConfigurationManager.fs and Lint.fs)

**Comment by duckmatt** [comment]
Uploaded [`0.4.6`](https://www.nuget.org/packages/FSharpLint.Core/0.4.6), thanks again for the PR :)

**Comment by duckmatt** [comment]
Had a look at VFPT as I noticed another problem which will be a memory leak of configurations as more projects are opened and closed (never removing on close) which I recall putting a solution in for, and it's using [yet another api on top of the configuration](https://github.com/fsprojects/FSharpLint/blob/master/src/FSharpLint.Core/Framework/Configuration.fs#L501). I'll merge these apis into a single module
