### ISSUE TITLE
Usage of PascalCase vs camelCase for Record Field Identifiers

### ISSUE THREAD

**Issue by haf** [fsprojects/FSharpLint#174]
Hi there,

I've been writing F# for a while now and all my libs are camelCase, as I think they should be. Could we change to camelCase for identifiers?

Relevant: https://github.com/ionide/ionide-vscode-fsharp/issues/148

**Comment by duckmatt** [comment]
Hi, by libs do you mean namespace names?

**Comment by haf** [comment]
Sure, stuff like this:

<img width="378" alt="screen shot 2016-08-24 at 14 57 42" src="https://cloud.githubusercontent.com/assets/193115/17931314/22c71d64-6a0b-11e6-8e62-f41151b44a2b.png">

**Comment by haf** [comment]
The rationale in your docs state:

<blockquote>
Suggested in F# Component Design Guidelines. A record field in C# will be a class property so it makes sense to have it be PascalCase as that's the convention for properties in .NET
</blockquote>

But I don't care about what C# sees my records as, since they aren't used from C#. This is F# and I want something nice looking for F#.

**Comment by duckmatt** [comment]
The linter hasn't hit `1.0` yet so the rules are still open for considerable change. There's an issue [here for cross referencing and re-evaluating all rules](https://github.com/fsprojects/FSharpLint/issues/162), it would be great to have members of the community with your experience influence the outcome of this.

I can see your point, PascalCase vs camelCase for record fields seems to vary by project, so perhaps the best case will be to disable the rule by default. The rule in question has come from the [F# guidelines](http://fsharp.org/specs/component-design-guidelines/#do-use-the-net-naming-and-capitalization-conventions-for-object-oriented-code-including-f-facing-libraries) (Table 1 Conventions Associated with Public Constructs in .NET Frameworks and Extensions for F# Constructs in F#-to-F# libraries) which is going to be the golden source for any rules implemented here.

**Comment by dsyme** [comment]
@duckmatt See my comment here: https://github.com/ionide/ionide-vscode-fsharp/issues/148#issuecomment-246694189

I think the main problem is that the message is too strong ("must" v. "suggested").    Also, it might actually make sense to remove this recommendation from the F# component guidelines in any case, or make it much weaker.

cheers
don

**Comment by duckmatt** [comment]
Thanks, I'm going to replace the message and also add an issue with a list of the current format strings to see if I can get some replacements suggested from the community, all of them can be improved :) 

I'm going to disable this rule by default as there doesn't seem to be a general consensus and it's currently varying by project, with some popular projects choosing camel case and some choosing pascal case (which is unfortunate when you reference one of each).

**Comment by duckmatt** [comment]
Warnings are updated in [0.4.8](https://www.nuget.org/packages/FSharpLint.Core/0.4.8), I've also added a [new issue to try to make it simpler for the community to suggest improvements](https://github.com/fsprojects/FSharpLint/issues/181). RecordFieldNamesMustBePascalCase is also now disabled by default.
