### ISSUE TITLE
MSBuild hangs forever with recursive calls to FSharp.Compiler.Service.ProjectCrackerTool.exe

### ISSUE THREAD

**Issue by blumu** [fsprojects/FSharpLint#177]
### Description

I followed instruction to hookup fslint with my project using msbuild.
When building the project msbuild hangs forever. CPU usage spikes to 100% making computer unusable. Process explorer reveals hundreds of copies of `FSharp.Compiler.Service.ProjectCrackerTool.exe` being recursively spawn.

![image](https://cloud.githubusercontent.com/assets/3913258/18216030/21ef7274-7109-11e6-8481-32aca95b91af.png)

**Comment by duckmatt** [comment]
Hi William, thanks for the report, is the version of FSharpLint [`FSharpLint.MSBuild 0.4.5`](https://www.nuget.org/packages/FSharpLint.MSBuild/)?

**Comment by blumu** [comment]
Yes. Here is the relevant part from my paket.lock file:
```
    FParsec (1.0.2)
    FsCheck (2.2.4) - framework: >= net452
      FSharp.Core (>= 3.1.2.5)
    FSharp.Compiler.Service (6.0.2)
      System.Collections.Immutable (>= 1.2)
      System.Reflection.Metadata (>= 1.4.1-beta-24227-04)
    FSharp.Compiler.Service.ProjectCracker (6.0.2)
    FSharp.Core (4.0.0.1)
    FSharp.Data (2.2.5) - framework: >= net45
    FSharpLint.Core (0.4.6)
      FParsec (>= 1.0.2)
      FSharp.Compiler.Service (>= 6.0)
      FSharp.Compiler.Service.ProjectCracker (>= 6.0)
    FSharpLint.Fake (0.4.3)
    FSharpLint.MSBuild (0.4.5)
```

**Comment by blumu** [comment]
@duckmatt The issue reproes with `0.4.4` but not with `0.4.3` so it must be a regression introduced on Saturday, July 23, 2016 since both versions were released on that day.

**Comment by blumu** [comment]
With `0.4.3` it actually fails with the following message:
```
 warning : Lint failed while analysing ...
 warning : Failed with: The system cannot find the file specified
 warning : Stack trace:    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStart
 warning :    at System.Diagnostics.Process.Start()\r
 warning :    at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCracker.GetProjectOptionsFromProjectFileLogged(String projectFileName, FSharpOption`1 properties, FSharpOption`1 loadedTimeStamp, FSharpOption`1 enableLogging)\r
 warning :    at FSharpLint.Application.Lint.getProjectFileInfo(String projectFilePath)\r
 warning :    at FSharpLint.Application.Lint.lintProject(OptionalLintParameters optionalPara
 warning :    at FSharpLint.Application.FSharpLintWorker.RunLint(String projectFile, OptionalLintParameters options, FSharpOption`1 progress)```

**Comment by duckmatt** [comment]
Thanks for checking - `0.4.3` is broken. I'm unable to reproduce on my machine, what's your environment setup? [Line which should prevent this from happening](https://github.com/fsprojects/FSharpLint/blob/master/src/FSharpLint.Core/Application/Lint.fs#L228)

**Comment by duckmatt** [comment]
Ignore my previous comment, have managed to repeat now (was installing via nuget, doing it manually as per the docs triggers the issue)

**Comment by duckmatt** [comment]
The docs are unfortunately fairly out of date. The code below from the docs:

```xml
<UsingTask AssemblyFile="$(SolutionDir)\packages\FSharpLint.MSBuild.0.4.5\tools\FSharpLint.MSBuild.dll" TaskName="FSharpLintTask" />
<Target Name="AfterBuild">
    <FSharpLintTask Project="$(MSBuildProjectFullPath)" />
</Target>
```

Should really be using the targets file as so:

```xml
<Import Project="$(SolutionDir)\packages\FSharpLint.MSBuild.0.4.5\build\FSharpLint.MSBuild.targets" />
```

**Comment by blumu** [comment]
Thanks, using `<Import>` instead of `<UsingTask>` solved the problem. Performance, though, is pretty bad: it takes longer to analyze one project than building my entire solution. Is this expected?

**Comment by duckmatt** [comment]
Ah great :). 

Yes, that's expected, the linting itself is pretty quick (average 1000 line file is less than 10ms on my low spec laptop). The project cracker (part of `FSharp.Compiler.Service`) which analyses the `.fsproj` slows things down significantly, it's also having to rebuild the AST (using `FSharp.Compiler.Service`) each time the task runs. Ionide and VFPT are both able to provide instant feedback as they already have the AST to hand (and don't need project info) - Ionide is using the most up to date version of FSharpLint, the version in VFPT is several months old

**Comment by duckmatt** [comment]
[Docs for the MSBuild task have been updated](http://fsprojects.github.io/FSharpLint/MSBuild-Task.html)
