### ISSUE TITLE
Handle international characters in identifiers

### ISSUE THREAD

**Issue by majocha** [fsprojects/FSharpLint#184]
### Description

Correctly capitalized identifiers containing national characters are flagged as incorrect casing

### Repro steps
eg.
`type Ścieżka = Ścieżka of string`
or
    
`let wczytaj ścieżka = ...`

### Expected behavior

Either handle such identifiers correctly or ignore them.

**Comment by duckmatt** [comment]
Thank you for reporting this. I've added your [reproduction as a regression test](https://github.com/fsprojects/FSharpLint/blob/master/tests/FSharpLint.Core.Tests/Rules/TestNameConventionRules.fs#L1215), the fix is in [`0.4.9`](https://www.nuget.org/packages/FSharpLint.Core/0.4.9)
