### ISSUE TITLE
Wrong suggestion to replace property assigning in constructor with property name

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/FSharpLint#186]
![image](https://cloud.githubusercontent.com/assets/873919/19269740/ecb71960-8fc4-11e6-866e-a32fc5be054f.png)

**Comment by duckmatt** [comment]
Thank you for reporting this

I'm currently unable to repeat:
![image](https://cloud.githubusercontent.com/assets/3247369/19280945/bff9832a-8fdf-11e6-9d7a-bfa323b68f56.png)

Are there any errors in the file when this bug appears? I'm able to get it to occur only when the type checker is unable to determine whether or not they are properties (if I remove `open System.Diagnostics`)
