### ISSUE TITLE
Incorrrect lint warning on usage of foldBack

### ISSUE THREAD

**Issue by rexcfnghk** [fsprojects/FSharpLint#189]
### Description

I am trying to reimplement the `List.distinct` function:

    let inline distinct list =
        let folder curr = function
            | [] -> [curr]
            | l -> if List.contains curr l then l else curr :: l
        List.foldBack folder list []
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
I got a lint warning that says

> List.foldBack f x [] might be able to be refactored into x

However that doesn't make much sense to me as this leads me to return the original list without performing the distinct logic.

### Repro steps

1. Enter the above `distinct` function in Visual Studio with F# Power Tools installed, or Visual Studio with Ionide-fsharp extension installed

### Expected behavior

No lint warnings

### Actual behavior

Lint warning:

> List.foldBack f x [] might be able to be refactored into x

### Known workarounds

No known workarounds

### Related information 

* Operating system: Windows 10
* Branch: N/A
* .NET Runtime, CoreCLR or Mono Version: 4.6.2
* Performance information, links to performance testing scripts: N/A

I am happy to help fix this, if someone can point me to the relevant sections of the source code.

**Comment by duckmatt** [comment]
Hi @rexcfnghk, thanks for the clear and detailed bug report. 

The erroneous code causing the bug in question [makes up part of the default config](https://github.com/fsprojects/FSharpLint/blob/master/src/FSharpLint.Core/DefaultConfiguration.FSharpLint), looks like the order of params on these hints needs to be switched (or these hints removed). It'd be great to have a contribution of this fix, I'll deploy it into the next version 

In terms of a current workaround: as these hints are configurable, a user will be able to setup their own config with the correct hints, unfortunate as the default hints shouldn't need to be corrected.
