### ISSUE TITLE
cyclomatic complexity removed?

### ISSUE THREAD

**Issue by jmecosta** [fsprojects/FSharpLint#195]
hi @duckmatt 

notice that the http://fsprojects.github.io/FSharpLint/CyclomaticComplexity.html has been removed from code. Is there a new replacement for it?

regards

jorge costa

**Comment by duckmatt** [comment]
Hi Jorge, 

It was removed during a reworking of the core of the linter, didn't seem like it was being used by any one so didn't deem it worthy of porting it across. Did you find it useful to have?

**Comment by jmecosta** [comment]
i was updating the F# sonar plugin and being complexity such a core metric in sonar its curious that no one is using it in F#. usually complexity gives good indication where we start refactoring and putting limits on it its good to keep the code simple to follow. 

maybe it does not apply to F#?

**Comment by duckmatt** [comment]
it can apply to f# but is certainly less useful than when applied to imperative languages, a pattern match against each case of a DU of *n* cases increases the CC of the func by *n*, with this it's easy to get a lot of "false positives" where refactoring the code to reduce the CC would probably make it more complex and less idomatic

**Comment by jmecosta** [comment]
OK @duckmatt, thanks for the explanation. I will follow this recommendation also
