### ISSUE TITLE
Change license from GPL to MIT

### ISSUE THREAD

**Issue by duckmatt** [fsprojects/FSharpLint#197]
Changing from GPL to MIT, the more permissive licence may encourage further integration/usage with other tools.

@archaeron @jhamm would you be happy for the code you have contributed to be moved to the MIT license?

**Comment by archaeron** [comment]
@duckmatt sure :) thx for asking

**Comment by duckmatt** [comment]
@archaeron great thank you :)

@jhamm to move over to MIT for now the xml doc rules will need to be taken out, please do let me know if you agree with the change in license - would love to be able to get the code back in
