### ISSUE TITLE
Customizable naming rules

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsprojects/FSharpLint#199]
Right now you can only enable / disable predefined rules.

I think it would be good idea if there were possibility of defining custom rules (for start choosing from  bigger predefined set - pascal, camel, pascal with underscores, camel with underscores, + defining prefixes and endings)  for all elements checked for naming rules. 

I guess I can try to implement it if you're OK with such feature.

**Comment by duckmatt** [comment]
Thanks for the suggestion :) would be a good improvement
