### ISSUE TITLE
Add suggested fix for naming rules

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsprojects/FSharpLint#205]
Should be pretty simple, requires setting fix in https://github.com/fsprojects/FSharpLint/blob/master/src/FSharpLint.Core/Rules/NameConventions.fs#L392

**Comment by duckmatt** [comment]
Would be good for removing underscores, adding prefixes and suffixes. might be a bit more difficult to try and correct the casing

**Comment by Krzysztof-Cieslak** [comment]
Right now we check only PascalCase and camelCase so I guess all we can do is check casing of first character

**Comment by duckmatt** [comment]
Good plan, went with that :) https://github.com/fsprojects/FSharpLint/pull/206
