### ISSUE TITLE
Update project to FCS 10?

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/FSharpLint#214]
There are breaking changes in FCS 10 that we would like to incorporate into VFPT.

Can we consider updating FSharpLint.Core to latest FCS?

https://github.com/fsprojects/VisualFSharpPowerTools/pull/1496

**Comment by duckmatt** [comment]
Yep, just updated: https://www.nuget.org/packages/FSharpLint.Core/0.6.5-beta
