### ISSUE TITLE
File name: Consider using PascalCase

### ISSUE THREAD

**Issue by alexpanter** [fsprojects/FSharpLint#240]
# foreword
This message is directly forwarded from fsharp-mode (Emacs package) at https://github.com/fsharp/emacs-fsharp-mode/issues/149.:

### Description

Getting a flycheck message "Consider changing `3i-3.fsx` to PascalCase". The filename cannot be translated to PascalCase - doesn't make sense. This is obviously a parse error somewhere. I think. :)

### Repro steps

1. Step A
Create a file with the given name.

2. Step B
Open it with Emacs [or any other text editor], fsharp-mode set to current major mode.

### Related information 

* Operating system
Ubuntu 16.04.3 LTS
* Branch
Using fsharp-mode version "20170918.842".
* Emacs version
24.5.1
* .NET Runtime, CoreCLR or Mono Version
5.2.0.244 (Mono)
4.1 (F# compiler)

**Comment by alexpanter** [comment]
## Update

The same behaviour has been observed in VIsual Studio Code.

**Comment by duckmatt** [comment]
Thank you for reporting this, I've included a fix in `0.8.2`

https://github.com/fsprojects/FSharpLint/pull/242
