### ISSUE TITLE
How to disable `The qualifier is redundant` warning

### ISSUE THREAD

**Issue by blumu** [fsprojects/FSharpLint#244]
### Description

Please provide a succinct description of your issue.
I am using VSCode which reports tons of `The qualifier is redundant` warnings. I would like to disable them but the doc does not explain how to configure this in the FSharpLint configuration file.

### Repro steps

Create some F# script with open statement and redundant qualifier references. Run it through fslint.

### Expected behavior

Documentation explaining how to disable the warnings.

### Actual behavior

fslint always report the noisy warnings.

### Known workarounds

None

### Related information 

* Operating system: Windows 10
* Branch: version shipping with Ionide-fsharp 3.12.4 for VSCode

**Comment by Krzysztof-Cieslak** [comment]
`The qualifier is redundant` is not provided by FSharpLint but is custom diagnostic implemented in FSAC. 

In VSCode you can disable it with `"FSharp.simplifyNameAnalyzer":false` setting.
