### ISSUE TITLE
Add Resharper like option to disable Lint in file

### ISSUE THREAD

**Issue by IvanAntipov** [fsprojects/FSharpLint#247]
It is common to have
module1.fs - file with production code
module1Playground.fsx - script file for problem investigation around logic in module1.fs

module1.fs - chould be well formated and checked for warning
module1Playground.fsx - is a playground, no need to format it well.

It will be convenient to have option to disable warnings in file like
Like
`// ReSharper Disable All`
directive

From
[https://github.com/ionide/ionide-vscode-fsharp/issues/700]

**Comment by duckmatt** [comment]
Thank you for the suggestion, it's a good idea

**Comment by jgardella** [comment]
This is available as of v0.13.1 using the [new structured comments for suppression](http://fsprojects.github.io/FSharpLint/Suppression.html). Specifically, you can put `// fsharplint:disable` at the top of the file to disable linting for the whole file.
