### ISSUE TITLE
FSharpLint.MSBuild on .NET Core results in StackOverflowException

### ISSUE THREAD

**Issue by ErikSchierboom** [fsprojects/FSharpLint#250]
### Description

When adding FSharpLint.MSBuild to a F# .NET Core project, building the project results in a `StackOverflowException`

### Repro steps

Please provide the steps required to reproduce the problem

1. Open Visual Studio 2017

2. File -> New Project -> Visual F# -> .NET Core -> Class Library (.NET Core)

3. Add `FSharpLint.MSBuild` NuGet package version `0.9.0`.

4. Try building the project.

### Expected behavior

The build succeeds and the project is linted correctly.

### Actual behavior

The build fails with an error:

``` 
Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception: Lint failed while analysing D:\Users\Erik\Documents\Persoonlijk\Programmeren\playground\FSharp\ClassLibrary1\ClassLibrary1.fsproj.
Failed with: error parsing ProjectCrackerTool output, stdoutput was:

stderr was:

Process is terminated due to StackOverflowException.

Stack trace:    at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCracker.GetProjectOptionsFromProjectFileLogged(String projectFileName, FSharpOption`1 properties, FSharpOption`1 loadedTimeStamp, FSharpOption`1 enableLogging)
   at FSharpLint.Application.Lint.getProjectFileInfo(String projectFilePath)
   at FSharpLint.Application.Lint.lintProject(OptionalLintParameters optionalParams, String projectFilePath, FSharpOption`1 progress)
   at FSharpLint.Application.FSharpLintWorker.RunLint(String projectFile, OptionalLintParameters options, FSharpOption`1 progress)
   at FSharpLint.MSBuild.AppDomain.LintRunner.Lint(String projectFile)
   at FSharpLint.MSBuild.AppDomain.LintRunner.Lint(String projectFile)
   at FSharpLint.MSBuild.Proxy.Lint()
   at FSharpLint.MSBuild.FSharpLintTask.Execute()
	ClassLibrary1	D:\Users\Erik\Documents\Persoonlijk\Programmeren\playground\FSharp\ClassLibrary1\ClassLibrary1.fsproj	1	
```

### Known workarounds

None

### Related information 

* Operating system: Windows 10
* Branch: version 0.9.0
* .NET Runtime: CoreCLR

**Comment by richardjharding** [comment]
I get something similar:

but the build error I see is

```
C:\Users\richa\.nuget\packages\fsharplint.msbuild\0.9.0\build\FSharpLint.MSBuild.targets(16,5): error MSB4062: The "FSharpLintTask" task could not be loaded from the assembly C:\Users\richa\.nuget\packages\fsharplint.msbuild\0.9.0\build\../tools/FSharpLint.MSBuild.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. 
```

**Comment by SteveGilham** [comment]
As linked above, I have a report of this same StackOverflowException, the circumstances being

* 0.9.1-beta MSBuild task
* Old-school .net framework solution

but I've never seen this behaviour myself.

**Comment by ErikSchierboom** [comment]
I have updated my .NET Core SDK to 2.1.104, and my previous error has been replaced by a new one (the same as @richardjharding):

<pre>
/Users/erikschierboom/.nuget/packages/fsharplint.msbuild/0.9.0/build/FSharpLint.MSBuild.targets(16,5): error MSB4062: The "FSharpLintTask" task could not be loaded from the assembly /Users/erikschierboom/.nuget/packages/fsharplint.msbuild/0.9.0/build/../tools/FSharpLint.MSBuild.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. [/Users/erikschierboom/Programming/exercism/fsharp/exercises/accumulate/Accumulate.fsproj]
/Users/erikschierboom/.nuget/packages/fsharplint.msbuild/0.9.0/build/FSharpLint.MSBuild.targets(16,5): error MSB4062:  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [/Users/erikschierboom/Programming/exercism/fsharp/exercises/accumulate/Accumulate.fsproj]
</pre>

**Comment by duckmatt** [comment]
Thanks for raising this, and sorry for the very delayed response! The MSBuild task has been deprecated, the linter is now best run as [dotnet tool](https://www.nuget.org/packages/dotnet-fsharplint/) or via Ionide
