### ISSUE TITLE
System.TypeInitializationException when attempting to use from .net core

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/FSharpLint#252]
### Description

The static initialization of `'FSharpLint.Framework.Configuration` uses an unqualified resource name, to wit `GetManifestResourceStream("DefaultConfiguration.FSharpLint")`; but .net core namespace qualifies resources, and the actual path in `fsharplint.core\0.9.0\lib\netstandard2.0\FSharpLint.Core.dll`  is `FSharpLint.Core.DefaultConfiguration.FSharpLint`. 

### Repro steps
Using a C# .net core project here to avoid issues of FSharp.Core versioning

Project file
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FSharpLint.Core" Version="0.9.0" />
    <PackageReference Include="FSharp.Core" Version="4.3.4" />
  </ItemGroup>

</Project>
```

Source file
```
using System;
using FSharpLint.Application;

namespace repro
{
    class Program
    {
        static void Main(string[] args)
        {
            var v2 = new Version("2.3.0.0");
            Console.WriteLine("{0}", Lint.lintSource(Lint.OptionalLintParameters.Default, "", v2));
        }
    }
}
```

then `dotnet run <project>.csproj`

### Expected behavior

A normal return from the program

### Actual behavior

```
System.TypeInitializationException: The type initializer for 'FSharpLint.Framework.Configuration' threw an exception. ---> System.TypeInitializationException: The type initializer for '<StartupCode$FSharpLint-Core>.$Configuration' threw an exception. ---> System.Exception: Resource 'DefaultConfiguration.FSharpLint' not found in assembly 'FSharpLint.Core, Version=0.9.0.0, Culture=neutral, PublicKeyToken=null'
```

### Known workarounds

Using a private patched version e.g. with code like

```
  let resourceName = Assembly.GetExecutingAssembly().GetManifestResourceNames()
                         |> Seq.find (fun n -> n.EndsWith("DefaultConfiguration.FSharpLint", StringComparison.Ordinal))

  use stream = assembly.GetManifestResourceStream(resourceName)
```
[at this point in the code](https://github.com/fsprojects/FSharpLint/blob/master/src/FSharpLint.Core/Framework/Configuration.fs#L448)

### Related information 

* Windows 10 v1709 Home
* Published nuget package v0.9.0
* dotnet --version 2.1.4

**Comment by SteveGilham** [comment]
Actually, I can repro the issue just by doing a build -- unit test failures everywhere.  This must be a recent behavioural change in .net core.

**Comment by SteveGilham** [comment]
I still don't have a clean build -- 11 unit test failures in the .net core tests , so no PR at the moment; but the same sort of resource namespacing is needed in [Resources.fs](https://github.com/fsprojects/FSharpLint/blob/1cae33d9699ae317c5449120e4dc05edf0474ff6/src/FSharpLint.Core/Framework/Resources.fs#L9)
```
    static let resourceName = Assembly.GetExecutingAssembly().GetManifestResourceNames()
                              |> Seq.find (fun n -> n.EndsWith("Text.resources", System.StringComparison.Ordinal))

    static let resourceManager = ResourceManager(resourceName.Replace(".resources", System.String.Empty), typeof<Resources>.GetTypeInfo().Assembly)
```

**Comment by SteveGilham** [comment]
Those 11 failing tests are exactly the ones in the recent commit https://github.com/fsprojects/FSharpLint/commit/221a07cf649cf8a822a59056d50d91501a461463, so it doesn't look like I've broken anything.

**Comment by duckmatt** [comment]
Thanks for raising this. It should be working now as the solution is now dotnet core first
