### ISSUE TITLE
0.9.1 is Broken in VS 15.7 and whatever other updates that brings

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/FSharpLint#263]
### Description
Lint fails with this error

```
       (FSharpLint target) ->
TypeLoadException: Could not load type 'Microsoft.FSharp.Control.CommonExtensions+SubscribeToObservable@1693' from assembly 'FSh
       arp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
error :    at FSharpLint.MSBuild.AppDomain.LintRunner.add_Failure(FailureEventHandler handler)
error :    at <StartupCode$FSharpLint-MSBuild>.$FSharpLintTask.Lint@26.Invoke(FailureEventHandler eventDelegate)
error :    at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.CreateEvent@341.System-IObservable`1-Subscribe(IObserver`1 r)
error :    at FSharpLint.MSBuild.Proxy.Lint()
error :    at FSharpLint.MSBuild.FSharpLintTask.Execute()
```
### Repro steps

Please provide the steps required to reproduce the problem

1. Load the current master (932c20d) of FSharpLint into VS 15.7

2. Run unit test FunctionalTestMSBuildTask

### Expected behavior

It passes

### Actual behavior

That test shows the essentially the same error  
```
error : TypeLoadException: Could not load type 'Microsoft.FSharp.Control.CommonExtensions+SubscribeToObservable@1693' from assembly 'FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
error :    at FSharpLint.MSBuild.AppDomain.LintRunner.add_Failure(FailureEventHandler handler)
error :    at <StartupCode$FSharpLint-MSBuild>.$FSharpLintTask.Lint@26.Invoke(FailureEventHandler eventDelegate
error :    at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.CreateEvent@341.System-IObservable`1-Subscribe(IObserver`1 r)
error :    at Microsoft.FSharp.Control.CommonExtensions.SubscribeToObservable[T](IObservable`1 x, FSharpFunc`2 callback)
error :    at Microsoft.FSharp.Control.CommonExtensions.AddToObservable[T](IObservable`1 x, FSharpFunc`2 callback)
error :    at FSharpLint.MSBuild.Proxy.Lint()
error :    at FSharpLint.MSBuild.FSharpLintTask.Execute()
```
### Known workarounds

N/A

### Related information 

* Operating system -- Win 10 Home
* Branch -- 0.9.1 NuGet release or master @ 932c20d
* .NET Runtime, CoreCLR or Mono Version
* Performance information, links to performance testing scripts

**Comment by SteveGilham** [comment]
This is blinking well baffling -- in FSharpCore 4.4.3.0, the nearest synthetic class is `Microsoft.FSharp.Control.CommonExtensions+SubscribeToObservable@1741`, so yes, there's going to be a failure to invoke the `@1693` variant; however there isn't any reference to any `SubscribeToObservable` in the IL for `add_Failure`
```
.method public hidebysig specialname 
	instance void add_Failure (
		class FSharpLint.MSBuild.AppDomain/FailureEventHandler 'handler'
	) cil managed 
{
	// Method begins at RVA 0x2928
	// Code size 21 (0x15)
	.maxstack 8

	IL_0000: nop
	IL_0001: ldarg.0
	IL_0002: ldfld class [FSharp.Core]Microsoft.FSharp.Control.FSharpEvent`2<class FSharpLint.MSBuild.AppDomain/FailureEventHandler, class FSharpLint.MSBuild.AppDomain/FailureEventArgs> FSharpLint.MSBuild.AppDomain/LintRunner::failureEvent
	IL_0007: callvirt instance class [FSharp.Core]Microsoft.FSharp.Control.IEvent`2<!0, !1> class [FSharp.Core]Microsoft.FSharp.Control.FSharpEvent`2<class FSharpLint.MSBuild.AppDomain/FailureEventHandler, class FSharpLint.MSBuild.AppDomain/FailureEventArgs>::get_Publish()
	IL_000c: ldarg.1
	IL_000d: tail.
	IL_000f: callvirt instance void class [FSharp.Core]Microsoft.FSharp.Control.IDelegateEvent`1<class FSharpLint.MSBuild.AppDomain/FailureEventHandler>::AddHandler(!0)
	IL_0014: ret
} // end of method LintRunner::add_Failure
```
and while JITting can pull code across assembly boundaries, I'm at a loss to see where it would be looking to find that other assembly version.

**Comment by SteveGilham** [comment]
I've found where the `@1693` version comes from.   In `C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.4.3.0`  I have FSharp.Core.dll with `[assembly: AssemblyFileVersion("2018.04.25.1")]` which has it.  The version of FSharp.Core.dll 4.4.3 packaged with 0.9.1 is `[assembly: AssemblyFileVersion("2018.01.25.1")]`; so some of the internals leak, enough that the implied contract of the assembly version (that one is a drop-in replacement of the other) is violated.

When I build the unit tests, version "2018.04.25.1" is present in `FSharpLint\tests\FSharpLint.FunctionalTest.TestedProject\bin\Debug`; but FSharpLint\tests\FSharpLint.FunctionalTest.TestedProject\FSharpLintMSBuildTaskTest contains version `[assembly: AssemblyFileVersion("2018.02.09.3")]`

Deleting every instance of FSharp.Core.dll under the repo root and rebuilding gets us past the first error and now fails with
```
Message: The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length. StackTrace:    at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.projectInstanceFromFullPath@76(FSharpList`1 properties, ProjectCollection engine, String fsprojFullPath)
```

We may have a work-around in the form of copying the reference "2018.04.25.1" version over the one in the expanded nuget package; but that would be rather flaky to export to the usual CI servers.

**Comment by duckmatt** [comment]
Thanks for taking a look into this. I've hit a similar issues before, the issues I've had in the past are that MSBuild tasks executed from VS pick up existing DLLs loaded by any VS extension or VS itself, this is where the usage of the AppDomain came from. Unfortunately FSharp.Core.dll doesn't seem to obey the usual AppDomain rules, if an AppDomain is started from F# it seems to still prefer the existing FSharp.Core.dll external to the AppDomain, I managed to work around this before by having a C# project create the AppDomain but became too much to maintain.

I'll try to get a version of the linter compiled against the more recent FSharp.Core on nuget, I think a good long term solution will be to replace the AppDomain with a seperate process

**Comment by SteveGilham** [comment]
Actually, it occurs to me that when operating within the classic framework, using a `ILMerge` to wedge everything together into an assembly with no external dependence on FSharp.Core would probably be the most durable solution.

**Comment by parthopdas** [comment]
@duckmatt Any updates on the a new version compiled against latest fsharp.core?

**Comment by duckmatt** [comment]
@parthopdas unfortunately it wasn't so simple as updating fsharp.core, I'm going to try and go with @SteveGilham 's solution (ilmerge to get a single msbuild task assembly) this weekend

**Comment by Horusiath** [comment]
Is there any chance for this to be fixed in the nearby future?

**Comment by SteveGilham** [comment]
Having experimented with adding a target to the current (legacy FAKE) build script
```
Target "Merge" (fun _ -> 
    let toolpath = findToolInSubPath "ILMerge.exe" "./packages"
    let files = !!("./src/FSharpLint.MSBuild/bin/Release/*.dll") 
                |> Seq.map FullName
                |> Seq.filter (fun f -> f <> FullName "./src/FSharpLint.MSBuild/bin/Release/FSharpLint.MSBuild.dll")

    ensureDirectory "./src/FSharpLint.MSBuild/bin/Merged"

    ILMerge (fun p -> { p with DebugInfo = true
                               ToolPath = toolpath
                               TargetKind = TargetKind.Library
                               Version = release.AssemblyVersion
                               Internalize = InternalizeTypes.Internalize
                               Libraries = files
                               TimeOut = TimeSpan(0, 10, 0)
                               AttributeFile = "./src/FSharpLint.MSBuild/bin/Release/FSharpLint.MSBuild.dll"})
                               "./src/FSharpLint.MSBuild/bin/Merged/FSharpLint.MSBuild.dll"
                               "./src/FSharpLint.MSBuild/bin/Release/FSharpLint.MSBuild.dll"
)
```
with the associated 1-line changes to `paket.dependencies` and the relevant `paket.template`, in the `update-dependencies` branch, touch-testing the build I had been using this with fails with
```
error : Failed with: Common Language Runtime detected an invalid program.
error : Stack trace:    at      Microsoft.FSharp.Compiler.TypeChecker.EstablishTypeDefinitionCores.structLayoutAttributeCheck@15116(range m, EntityRef thisTyconRef, FSharpOption`1 structLayoutAttr, Boolean allowed)
```
so this may be a dead-end.

**Comment by duckmatt** [comment]
@SteveGilham Yeah, I couldn't get ILMerge working with the FSharpLint assemblies, instead I did something I had wanted to do for a long time and deprecated the MSBuild task :P Might bring the MSBuild and Fake tasks back at some point but if I do they'll be wrappers around the new [dotnet tool](https://www.nuget.org/packages/dotnet-fsharplint/), to avoid these dependency issues that could never quite be resolved
