### ISSUE TITLE
[feature request] `(x: type)` vs `(x : type)` rule

### ISSUE THREAD

**Issue by samuela** [fsprojects/FSharpLint#276]
### Description

It would be nice to have a rule that guarantees consistency between whether or not there's a space before the colon in type defs.

**Comment by jgardella** [comment]
Hi samuela.

I recently added this in the new Formatting analyser; the rule is called `TypedItemSpacing`. Currently it is hardcoded to only accept the case `(x : type)`. We may want to make this a configurable setting; the three cases I've seen used in F# code are:

- space after `(x: type)`
- space before and after `(x : type)`
- no spaces `(x:type)`

So it may be a good idea to add support for the other two cases.
