### ISSUE TITLE
Documentation for FAKE and MSBuild has disappeared

### ISSUE THREAD

**Issue by nickcowle** [fsprojects/FSharpLint#291]
### Description

When #277 was merged, the documentation on how to use FSharpLint with FAKE and MSBuild was deleted (FAKE-Task.md and MSBuild-Task.md). However, links to these files are still present on https://fsprojects.github.io/FSharpLint/ (see the section "Running The Tool").

### Repro steps

1. Go to https://fsprojects.github.io/FSharpLint/

2. Click the link "Running the MSBuild task." or "Running the FAKE task."

### Expected behavior

Documentation on how to use FSharpLint with FAKE/MSBuild is displayed.

### Actual behavior

A 404 page is displayed.

### Known workarounds

You can still find the old documentation by going back through the commit history of the repo - https://github.com/fsprojects/FSharpLint/tree/0846153d30d4b598e6084992a1fc7ccbde6e7509/docs/content still has the files.

### Related information 

None that I can think of!

**Comment by duckmatt** [comment]
Thanks, this is a good find. For now the MSBuild task and Fake task have been deprecated. I'll update the docs to mention this and provide the reasoning behind it

**Comment by duckmatt** [comment]
Thanks for raising this, I've updated the docs to give a bit of background on why these have disappeared. For now if you'd want to run as part of a build I'd recommend using fake dotnet task to execute `dotnet fsharplint -f xyz.fsproj`
