### ISSUE TITLE
false positive tuple warning when using line break instead of empty space

### ISSUE THREAD

**Issue by forki** [fsprojects/FSharpLint#301]
![image](https://user-images.githubusercontent.com/57396/51986391-70f54400-24a0-11e9-9ec1-713b0733b3f0.png)

**Comment by Krzysztof-Cieslak** [comment]
I just want to say sorry to @jgardella and @duckmatt - enabling new version in Ionide had a nasty side effect of more bug reports ;-) I guess I should start contributing more again.

**Comment by jgardella** [comment]
@Krzysztof-Cieslak More bug reports is good!

@duckmatt recently released a new version with the Formatting linter disabled by default. I think this is sensible for now as there were some defaults in this new analyser that were not as widely accepted as I had thought. Should we push a new version of Ionide with that FSharpLint version (I believe `0.10.3`) to avoid disrupting people's workflows, while we work on more sensible defaults?

**Comment by forki** [comment]
Yeah Software without users does not have bugs.

**Comment by Krzysztof-Cieslak** [comment]
> Yeah Software without users does not have bugs.

That's my favourite kind of software, tho... 

> Should we push a new version of Ionide with that FSharpLint version

Yes, I'll do that... soon-ish
