### ISSUE TITLE
FSharpLint throws errors over op_Explicit

### ISSUE THREAD

**Issue by Shmew** [fsprojects/FSharpLint#323]
`static member op_Explicit(ExampleType e) = e`

Currently throws errors for both not using PascalCase and underscores. This is an issue as it is required to convert an arbitrary from generated types during property based testing.

See [here](https://github.com/fsharp/fsharp/blob/6819e1c769269edefcea2263c98f993e90b623e2/src/fsharp/FSharp.Core/prim-types.fs#L3687) and [here](https://github.com/fscheck/FsCheck/blob/8e41cf9b4b81e460ed4a46c89e95126ca596c1ae/src/FsCheck/Arbitrary.fs#L19).

**Comment by jgardella** [comment]
Hi @Shmew, thanks for the report.

I think a reasonable solution for this is to ignore the naming conventions rules for members which start with `op_`, since they are a special case used for operator overloading. I've implemented this in #324.
