### ISSUE TITLE
Need greater flexibility for suppressing warnings

### ISSUE THREAD

**Issue by anchann** [fsprojects/FSharpLint#345]
### Description

The current warning suppression mechanism is severely underpowered, and does not match the complexity of the real world we need to deal with.

Concretely, I want to enforce PascalCase on record field names, yet there are a couple of classes of use cases for which I need to be able to override/suppress:

* typing payloads of external APIs beyond my control — typically JSON payloads have camelCased field names, or even completely arbitrary ones.
* type wrappers for external React components and their props — typically these will be camelCased

The number of fields that trigger warnings are large, so sprinkling the entire type definition with a `SuppressMessage` attribute per line is noisy and redundant, killing readability. Excluding the file from linting entirely is highly undesirable.

I haven't read the docs, but I get the impression, given the fully qualified name, that "System.Diagnostics.CodeAnalysis.SuppressMessage" is some top level construct unrelated to the linter. So the linter raises all errors based on the json config, and only then does a subset of them get suppressed, before being passed on to the IDE/console for display. I wonder if much flexibility can be gained by the linter actually taking instructions on whether to emit messages _in the first place_. Given that attributes are rather inflexible, I think structured control comments, like ones used by tslint, would be the way to go. For reference: https://palantir.github.io/tslint/usage/rule-flags/

**Comment by jgardella** [comment]
Thanks for the suggestion, this has been something I've been thinking about for a while too and finally got around to implementing it. See here for details: http://fsprojects.github.io/FSharpLint/Suppression.html

**Comment by knocte** [comment]
> See here for details: http://fsprojects.github.io/FSharpLint/Suppression.html

Broken link. New link:
https://fsprojects.github.io/FSharpLint/how-tos/rule-suppression.html

(HTH anyone finding this via googling.)
