### ISSUE TITLE
Readme.md outdated

### ISSUE THREAD

**Issue by milbrandt** [fsprojects/FSharpLint#355]
### Description

`Readme.md` seems to be outdated and badges are broken.

### Repro steps

Just have a look at the `Readme.md` of current master.

### Expected behavior

Updated `Readme.md` to reflect current Situation and remove (or replace) broken badges.
Seems like the `Readme.md` was not updated for the large redesign PR #330 .

### Actual behavior

- Badges of issue stats are broken. Seems that issuestats.com has issues. See https://github.com/hstove/issue_stats/issues/50
- `Readme.md` reads as  _The tool is configurable via XML and can be run from a console app, or as an MSBuild task. _ whereas on http://fsprojects.github.io/FSharpLint/ the description tells _Configuration of the tool is done using JSON._

### Known workarounds

Either read http://fsprojects.github.io/FSharpLint/ or use `src/FSharpLint.Core/Application/XmlConfiguration.fs` to convert XML configuration to JSON.

### Related information
* Commit 0aa9108
* Branch master

**Comment by jgardella** [comment]
Thanks for the report, README is updated.
