### ISSUE TITLE
[Request] postfix generics syntax for a set of types, per Style Guide

### ISSUE THREAD

**Issue by reaysawa** [fsprojects/FSharpLint#365]
https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#use-prefix-syntax-for-generics-foot-in-preference-to-postfix-syntax-t-foo

I'm also happy to know, if this can't be reasonably achieved or isn't welcome here, the why.

**Comment by jgardella** [comment]
Hi @reaysawa,

Not sure if I'm missing something, but this should already be supported through the [typePrefixing](https://github.com/fsprojects/FSharpLint/blob/master/src/FSharpLint.Core/DefaultConfiguration.json#L12) rule, which is disabled by default; you would just have to enable it.

**Comment by reaysawa** [comment]
Hi @jgardella, I couldn't find it when I tried. I tried to search for "postFix", "generics", and related words from the Style Guide's hint I could intuit, but none matched.

Is that option missing some explanation for what it does? I couldn't find anything in either the website or the docs-gen folder.

**Comment by reaysawa** [comment]
the title no longer applies for that other problem, so I'm closing this issue
