### ISSUE TITLE
Override configuration's path through a CLI flag

### ISSUE THREAD

**Issue by resolritter** [fsprojects/FSharpLint#366]
Other linting tools offer this kind of customization. 

- [clang-tidy's --config](https://clang.llvm.org/extra/clang-tidy/#id2)
- [eslint's --config](https://eslint.org/docs/user-guide/command-line-interface#options)
- etcetera

The approach taken here for finding configuration files through the project's path is very unpractical sometimes. What about a way to specify a custom config when linting single files?

**Comment by jgardella** [comment]
Thanks for the suggestion, as of v0.13.2 this is supported with the `--lint-config` flag.
