### ISSUE TITLE
Rule FL0016 "failwithWithSingleArgument" missing

### ISSUE THREAD

**Issue by milbrandt** [fsprojects/FSharpLint#393]
### Description

Rule description http://fsprojects.github.io/FSharpLint/rules/FL0016.html

In [DefaultConfiguration.json](https://github.com/fsprojects/FSharpLint/blob/master/src/FSharpLint.Core/DefaultConfiguration.json) the configuration `failwithWithSingleArgument` is missing.

### Expected behavior

All rules are implemeneted and configured in `DefaultConfiguration.json`

### Actual behavior

Could not find `failwithWithSingleArgument`. Neither in `DefaultConfiguration.json` nor in `Configuration.fs`.

### Known workarounds

none

### Related information

* Branch master
Commit c5e8d54aab7251ba315f86563ebeaa656be56f14 of 2020-03-23

**Comment by duckmatt** [comment]
Thank you, you're right, I've added this back in via https://github.com/fsprojects/FSharpLint/pull/409
