### ISSUE TITLE
New nuget release

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsprojects/FSharpLint#410]
Hey, 

Could you do new release of NuGet package? In general, we'd love to see releases after updating FCS as quickly as possible - otherwise, it's blocking us in FSAC/Ionide.

**Comment by duckmatt** [comment]
Apologies for the slowness on this, it was supposed to be released a few days back but the pipeline appears to be failing on master, taking a look

**Comment by duckmatt** [comment]
CI issue resolved via https://github.com/fsprojects/FSharpLint/pull/411, released `0.14.0`

**Comment by Krzysztof-Cieslak** [comment]
Awesome, thanks a lot ❤️
