### ISSUE TITLE
error getting FSC args from msbuild info,

### ISSUE THREAD

**Issue by nojaf** [fsprojects/FSharpLint#412]
### Description

I could not lint the [Fantomas project](https://github.com/fsprojects/fantomas) via command line tool.

### Repro steps

Please provide the steps required to reproduce the problem

1. Fork Fantomas

2. Install local tool

> dotnet tool install dotnet-fsharplint

3. Run tool

>  dotnet fsharplint lint .\fantomas.sln

### Expected behavior

Tools works and points out what code can use improvements.

### Actual behavior

```
❯ dotnet fsharplint lint .\fantomas.sln
Lint failed while analysing .\fantomas.sln.
Failed with: error getting FSC args from msbuild info, MSBuildSkippedTarget
Stack trace:    at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1647.Invoke(String message)
   at FSharpLint.Application.Lint.lintProject$cont@427(OptionalLintParameters optionalParams, String projectFilePath, Unit unitVar) in C:\projects\fsharplint-231\src\FSharpLint.Core\Application\Lint.fs:line 471
   at FSharpLint.Application.Lint.lintSolution$cont@486(OptionalLintParameters optionalParams, String solutionFilePath, Unit unitVar) in C:\projects\fsharplint-231\src\FSharpLint.Core\Application\Lint.fs:line 511
   at FSharpLint.Console.Program.start(ParseResults`1 arguments) in C:\projects\fsharplint-231\src\FSharpLint.Console\Program.fs:line 126
```

### Known workarounds

/

### Related information

* Operating system: Windows 10
* .NET Runtime, CoreCLR or Mono Version: dotnet core sdk 3.1.101

**Comment by milbrandt** [comment]
Why are you are using `<TargetFrameworks>netstandard2.0</TargetFrameworks>`? As only netstandard2.0 is targeted, just use `<TargetFramework>`. I assume it will work then.

In #403 I observed the same issue for `TargetFrameworks` for multi-targetting netcoreapp2.1 and 3.1.

**Comment by Shmew** [comment]
I get the same error when using `<TargetFramework>netstandard2.0</TargetFramework>`

**Comment by jgardella** [comment]
Hey @nojaf, thanks for the detailed report and sorry for the delayed response.

This error comes up when you have a project with `TargetFrameworks`, which we are working on fixing. I tried to fork Fantomas and reproduce but I didn't have any issues; I think you may have removed the multi-targeting since you reported this issue. Could you confirm it's working now? If you have any other issues please share. Thanks.

**Comment by nojaf** [comment]
Hey @jgardella , we did indeed change TargetFrameworks to TargetFramework.
I had the same problem as @Shmew that is didn't appear to resolve the issue.
I'll check again tomorrow to verify your findings.

**Comment by Shmew** [comment]
I solved the problem when I updated the script I use that programmatically runs FSharpLint (so I can generate an xml report to publish to Azure DevOps).

**Comment by nojaf** [comment]
After trying this again @jgardella it worked just fine.
Thanks everybody for the assist.
