### ISSUE TITLE
Error when trying to install dotnet-fsharplint nuget package

### ISSUE THREAD

**Issue by fmarcondes08** [fsprojects/FSharpLint#531]
### Description

Hello, I'm trying to install the nuget package dotnet-fsharplint but I got an error.

![image](https://user-images.githubusercontent.com/25185823/146452735-e4558a3c-e64a-4300-b43b-7dbc0ef9bca7.png)

Did anyone get the same error? 

### Repro steps

1. Open nuget package manager
2. search for dotnet-fsharplint
3. Click install

### Related information

* Windows 10
* .Net 5.0

**Comment by knocte** [comment]
Just curious, why do you want to install the nuget pkg instead of using it as a dotnet tool?

**Comment by fmarcondes08** [comment]
I resolved to add the command line to install on project pre-building.

I tried to do something automatically because we don't want any developers to need to install it manually.

**Comment by knocte** [comment]
Why do you close the issue? The error is gone?
