### ISSUE TITLE
[Feature] Rule to discourage the use of keyword 'new' if type is not IDisposable

### ISSUE THREAD

**Issue by knocte** [fsprojects/FSharpLint#540]

**Comment by smoothdeveloper** [comment]
I'd like this, but wonder if FSharpLint already work on the typechecked data rather than just the syntactical AST?

**Comment by knocte** [comment]
> but wonder if FSharpLint already work on the typechecked data rather than just the syntactical AST?

Yes, sure, FSharpLint can work with the typechecked data too. For an example, check this recently merged PR: https://github.com/fsprojects/FSharpLint/pull/527

**Comment by knocte** [comment]
D'oh! The rule already exists!: https://fsprojects.github.io/FSharpLint/how-tos/rules/FL0014.html So sorry for the noise.
