### ISSUE TITLE
Provide instructions on how to debug FSharpLint cloned locally

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/FSharpLint#582]
As mentioned in #580, I have cloned FSharpLint locally and would like to debug a bug. However, I have no idea how to do this. Can the readme or similar be extended with information on how to do this? (Even just doing it here would be of great help.)

**Comment by cmeeren** [comment]
Would it be possible to get some help here? I'd like to try to contribute, but I have no idea how to debug FSharpLint locally.

**Comment by parhamsaremi** [comment]
Can you elaborate more on your problem? I'm using Visual Studio, and I use Test Explorer when I want to debug. [Here](https://learn.microsoft.com/en-us/visualstudio/test/debug-unit-tests-with-test-explorer?view=vs-2022) is a useful link for using Test Explorer. Feel free to ask any questions if you still have problems with this, and please let me know if using Test Explorer fixes your problem.

**Comment by cmeeren** [comment]
Nevermind, I managed to get it working by running FSharpLint.Console with a run config that specified the project I wanted to run against.

However, even while debgging, I was unable to get any more information than the stack trace I posted in #580. So for now, I have given up on FSharpLint.
