### ISSUE TITLE
PascalCase rule is wrong on generic arguments?

### ISSUE THREAD

**Issue by Thorium** [fsprojects/FSharpLint#610]
I run FSharpLint on itself and it gave a result:

```
Consider changing `t` to PascalCase.
Error on line 87 starting at column 16
    type Result<'t> =
                ^
```

Is `'t` not Pascal Case? It starts with quote-character `'`, which can be considered as upper-case and thus it can be thought of being PascalCase?

Besides of this, having `'T` is very C-Sharppy-thing and typically F# generics are `'a` and `'b`.
So I think the rule is wrong.

**Comment by bartelink** [comment]
MS examples use PascalCase e.g. https://learn.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-explicit-generic-type-arguments-and-constraints
