### ISSUE TITLE
"Doesn't run" with SDK 8.0.101

### ISSUE THREAD

**Issue by SeanTAllen** [fsprojects/FSharpLint#690]
### Description

We upgraded to FSharpLint 0.24.0 from 0.21.10. Linting works fine when run locally with SDK 8.0.100. It fails when run locally with 8.0.101 where it only prints a single no warnings:

`========== Summary: 0 warnings ==========` 

We introduced an intentional lint failure, it is found when using SDK 8.0.100, and nothing is found with SDK 8.0.101. The problem appears unrelated to FSharpLint version change as we can duplicate with every version of FSharpLint 0.21.4 and up. I didn't test with anything prior to 0.21.10.

Notes: 

- This is all with the dotnet tool.
- This is running across a solution like `dotnet dotnet-fsharplint lint Foo.sln`

### Repro steps

1. have some code that would cause linting error
2. install 0.24.0 of FSharpLint dotnet tool
3. install SDK 8.0.101
4. lint the code

### Expected behavior

I expect that when run with 8.0.101 that we would get the same correct results as with 8.0.100

### Actual behavior

Linting appears to not run and only:

`========== Summary: 0 warnings ==========` 

appears

### Known workarounds

Downgrade to 8.0.100

### Related information

This happens both locally with MacOS and in the latest mcr.microsoft.com/dotnet/sdk:8.0 image.

**Comment by knocte** [comment]
Hello @SeanTAllen thanks for reporting this bug!

> we can duplicate with every version of FSharpLint 0.21.4 and up.

Does this mean that the bug doesn't exist in v0.21.3? Or that you simply didn't test older versions than 0.21.4?

**Comment by SeanTAllen** [comment]
Didn't test older versions

**Comment by SeanTAllen** [comment]
With SDK 8.0.201 and the 0.24.2 linter release, I can no longer recreate this issue.

**Comment by knocte** [comment]
Thanks @SeanTAllen !
