### ISSUE TITLE
Add XmlDoc config options to only apply the rules to constructs with a given access

### ISSUE THREAD

**Issue by duckmatt** [fsprojects/FSharpLint#89]
A good addition to the tool would be to add a config option to the XmlDoc rules that allows the user to specify what access the constructs must have for a warning to be generated when the construct has no xml documentation e.g. only warn for public constructs.

**Comment by jhamm** [comment]
I will work on this one.

**Comment by jhamm** [comment]
Thanks! This was merged with #93 and can be closed.

**Comment by duckmatt** [comment]
Thanks @jhamm
