### ISSUE TITLE
fsharplint crashes VS2013 when Debug Selected Tests run from Test Explorer window

### ISSUE THREAD

**Issue by cljponies** [fsprojects/FSharpLint#90]
fsharplint 0.1.16
Visual Studio 2013 Update 4
xUnit.net 2.1.0-beta2-build2981
xUnit.net [Runner: Visual Studio] 2.1.0-beta2-build1055 
unquote 3.0.0

I added fsharplint to a F# library project and then referenced that assembly in a separate f# test library project.

I get consistent crash when I use above configuration, and right-click a test in Test Explorer window and select Debug Selected Tests item. I can run tests normally however (not debugging). For example, I can right-click on a test and choose Run Selected Tests and that works fine.

Removing fsharplint from my library project, stops VS from crashing, and I can again Debug Selected Tests from the Test Explorer window.

**Comment by duckmatt** [comment]
Thanks for reporting this, I'll try to see if I can recreate it

**Comment by cljponies** [comment]
I added by right-clicking References in my project in VS2013, and choosing Manage Nuget Packages...

**Comment by duckmatt** [comment]
Thanks, seems to crash for me whenever the solution is built via the test explorer

The last visual studio log (but doesn't seem relevant) I get is:

    <entry>
        <record>597</record>
        <time>2015/05/28 19:42:14.827</time>
        <type>Error</type>
        <source>Extension Manager</source>
        <description>Extension will not be loaded because an extension with the same ID &apos;Microsoft.Windows.DevelopmentKit.Desktop&apos; is already loaded at C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\MICROSOFT\WINDOWS KITS\8.0\DESKTOP SDK\...</description>
        <path>C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\MICROSOFT\WINDOWS KITS\8.1\DESKTOP SDK\</path>
    </entry>

I'll try to get this fixed for 0.2.0

**Comment by duckmatt** [comment]
346b026 appears to have fixed this issue on my machine. It would cause msbuild to crash, but only when it was run from within another program and unfortunately didn't output any errors to the msbuild logs

**Comment by duckmatt** [comment]
Could you try with [0.2.1](https://www.nuget.org/packages/FSharpLint/) please to see if this has been fixed?

**Comment by duckmatt** [comment]
I'm going to close this as the similar repeatable bug was fixed by this - please let me know if it wasn't fixed for you so I can reopen

**Comment by cljponies** [comment]
I agree. Looks like 0.2.1 has fixed this issue for me. Thanks.
