### ISSUE TITLE
FsharpLint is leaking memory with VS2013

### ISSUE THREAD

**Issue by dmich2** [fsprojects/FSharpLint#98]
fsharplint 0.2.2
Visual Studio 2013 Update 4
Windows 7 64bit

I'm trying to track down why VS2013 occasionally uses up to 2.6GB of memory even for a fairly tiny F# program. I disabled Visual F# Power Tools and FSharpLint and noticed that devenv.exe used about 320MB.

I just re-added FSharpLint, and now the memory usage is already up to 710MB and growing. It's seems like each time I rebuild devenv uses another 50MB?

**Comment by duckmatt** [comment]
Thanks for the report, I'm also able to reproduce this. I think this is because the msbuild task is never unloading the appdomain the linter is being run in - will look further into it when I get home tonight

**Comment by duckmatt** [comment]
I've updated the [package](https://www.nuget.org/packages/FSharpLint/0.2.3) would you be able to see if the issue is still present? thanks

**Comment by dmich2** [comment]
Just tried v0.2.3 and can confirm that bug is fixed.

**Comment by duckmatt** [comment]
Great, thanks :)
