### ISSUE TITLE
Duplicated warning

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/FSharpLint#99]
![image](https://cloud.githubusercontent.com/assets/873919/8511276/e735f062-2317-11e5-9338-63041587d90a.png)

**Comment by duckmatt** [comment]
Thanks for the report

[Location of the issue](https://github.com/fsharp/FSharp.Data/blob/7caa9ed507dc0c69abc39ed438acb5af81080abd/src/Html/HtmlParser.fs#L142)

**Comment by duckmatt** [comment]
This should be fixed in [`0.0.3`](https://www.nuget.org/packages/FSharpLint.Core/)

**Comment by vasily-kirichenko** [comment]
It's not fixed in 0.0.3

**Comment by duckmatt** [comment]
Sorry, I managed to upload assemblies from the wrong directory, I'll get a new package uploaded later today, which will hopefully also include a fix for #103 if i get time tonight

**Comment by vasily-kirichenko** [comment]
Fixed in 0.0.5
